# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1ff77f37375f9a6603f22ecd67e5e832"
name = "Honey Birdette Checkout (AMD)"
handle = "honey-birdette-checkout-amd"
application_url = "https://relatively-russia-proceed-hiking.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "amd-checkout-2024.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://relatively-russia-proceed-hiking.trycloudflare.com/auth/callback",
  "https://relatively-russia-proceed-hiking.trycloudflare.com/auth/shopify/callback",
  "https://relatively-russia-proceed-hiking.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
